baseURL = "https://juliusreade.com/"
languageCode = "en-gb"
title = "Julius Reade"
theme = "reade"

googleAnalytics = "UA-85083093-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "#YOLO."
  images = ["images/me/cool2.jpeg"] # TODO: make this into a square image
  title = "Julius Reade"
